### ISSUE TITLE
Show guest status when a dancer/student checks in

### ISSUE THREAD

**Issue by missmaggiemo** [mission-city-swing/mcs_registration#85]
Some dancers and students are guests of the venue. We'd like to be able to note when the dancer checks in that they are a guest and therefore don't have to pay.

**Comment by neilfitz** [comment]
@missmaggiemo Do you mean that we'd store the data on who guests are so that the volunteer knows? Or that there would be a checkbox we'd check?

**Comment by missmaggiemo** [comment]
https://github.com/mission-city-swing/mcs_registration/pull/116
