### ISSUE TITLE
Hide peoples contact info when auto-filling the check-in form

### ISSUE THREAD

**Issue by jmrgibson** [mission-city-swing/mcs_registration#86]
Kinda a privacy issue that anyone has access to look up peoples contact info by name via the autocomplete

Instead of displaying `joel.is.awesome@gmail.com`, we could display `jo********me@gmail.com`

**Comment by neilfitz** [comment]
nope this is hard

**Comment by missmaggiemo** [comment]
I'm going to call this a won't-fix for now, unless someone feels really passionate about it.
